-- 모의고사 성적 테이블 생성
create table exam_scores (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_name text not null,
  exam_name text not null,
  round integer not null,
  score integer not null
);

-- RLS(Row Level Security) 정책 설정
alter table exam_scores enable row level security;

-- 모든 사용자가 읽기 가능하도록 정책 설정
create policy "모든 사용자가 성적을 볼 수 있음" on exam_scores
  for select using (true);

-- 인증된 사용자만 성적을 추가할 수 있도록 정책 설정
create policy "인증된 사용자만 성적을 추가할 수 있음" on exam_scores
  for insert with check (auth.role() = 'authenticated');

-- 인덱스 생성
create index exam_scores_student_name_idx on exam_scores(student_name);
create index exam_scores_exam_name_idx on exam_scores(exam_name);
create index exam_scores_round_idx on exam_scores(round); 